app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('loja/', include('loja.urls', namespace='loja')),
    path('produto/', include('produto.urls', namespace='produto')),
    path('estoque/', include('estoque.urls', namespace='estoque')),
    path('caixa/', include('caixa.urls', namespace='caixa')),
    path('pedido/', include('pedido.urls', namespace='pedido')),
]
urlpatterns += [path("accounts", include("django.contrib.auth.urls"))]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/caixa/urls.py
from django.urls import path
from .views import *

app_name = "caixa"


urlpatterns = [
    path('', caixa_home, name='caixa_home'),
    path('registra', caixa_add, name='caixa_add'),
    path('registradora-<int:pk>/', registradora_home, name='registradora_home'),
    path('<int:pk>/item', registradora_item, name='registradora_Item'),
    path('busca-<int:pk>', busca_produto, name='query'),
    path('obs', observacao, name='observacao'),
    path('delete', registradora_remover_item, name='registradora_remove'),
    path('acres', registradora_acrecimo, name='registradora_acrescimo'),
    path('<int:pk>/acrescimo_list', acrescimo_list, name='acrescimo_list'),
    path('<int:pk>/enviado', registradora_pedido, name='registradora_pedido'),
    path('<int:pk>/entrega', registradora_entrega, name='registradora_entrega'),
    path('<int:pk>/pagamento', registradora_pagamento, name='registradora_pagamento'),
    path('<int:pk>/enviado_pedido', registradora_aceitar_pedido, name='registradora_aceitar_pedido'),
    path('<int:pk>/balcao', registradora_retirar_balcao, name='registradora_retirar_balcao'),
    path('<int:pk>/mesa', registradora_retirar_mesa, name='registradora_retirar_mesa'),
    path('<int:pk>/fecharmesa', fechar_mesa, name='fechar_mesa'),
    path('<int:pk>/pagamento_mesa', registradora_pagamento_mesa, name='registradora_pagamento_mesa'),
    path('<int:pk>/fechado', registradora_mesa_receber, name="registradora_mesa_receber"),

]

app/pedido/urls.py
from django.urls import path
from .views import *

app_name = "pedido"


urlpatterns = [
    path('item/', pedido_item, name='pedido_Item'),
    #path('', pedido_List, name='pedido_list'),
    path('obs', observacao, name='observacao'),
    path('delete', remover_item, name='remove'),
    path('acres', pedido_acrecimo, name='acrescimo'),
    path('<int:pk>/acrescimo_list', acrescimo_list, name='acrescimo_list'),

      #CONTROLE DE MESAS
    path('mesa_lista/', mesa_list, name='mesa_list'),
    path('mesa_criar/', mesa_criar, name='mesa_criar'),
    path('pedido_criar/', pedido_criar, name='pedido_criar'),
    path('<int:pk>_del_ped', pedido_delete, name='pedido_delete'),
    path('<int:pk>del_mesa', mesa_delete, name='mesa_delete'),
    path('<int:pk>ler_pedido', ler_pedido, name='ler_pedido'),
    path('<int:pk>pronto', pedido_pronto, name='pedido_pronto'),
    path('<int:pk>recebido', pedido_recebido, name='pedido_recebido'),
]

app/caixa/models.py
from django.db import models
from loja.models import Loja_Model

# Create your models here.
class Caixa(models.Model):
    loja = models.ForeignKey(Loja_Model, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now=True)
    descricao =  models.CharField(max_length=300, null=True, blank=True)
    valor = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    dinheiro = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    pix = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    debito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    credito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fiado = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    tipo = models.CharField(max_length=7, null=True, blank=True)
    objects = models.Manager()

    def __str__(self):
        return str(self.pk)
    
    

app/pedido/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from loja.models import *
# from cliente.models import *
from produto.models import *

# Create your models here.
class Mesa(models.Model):
    loja = models.ForeignKey(Loja_Model, on_delete=models.CASCADE)
    numero = models.CharField(max_length=10,null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dinheiro = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    pix = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    debito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    credito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fiado = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    frm_pg = models.CharField(max_length=30, null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True, default='aberto')
    objects = models.Manager()


    def __str__(self):
        return str(f' Pedido: {self.pk} Mesa: {self.numero}')
    
    def get_mesa_url(self):
       return reverse_lazy("caixa:fechar_mesa", kwargs={"pk":self.pk})



class Pedido(models.Model):
    dia = models.DateField(auto_now_add=True)
    loja = models.ForeignKey(Loja_Model, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    mesa = models.ForeignKey(Mesa, related_name='ped_mesa',null=True, blank=True, on_delete=models.CASCADE)
    venda = models.CharField(max_length=10, null=True, blank=True)
    pedido = models.TextField(null=True, blank=True)
    total_pedido = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    nome = models.CharField(max_length=200, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    cep = models.CharField(max_length=30, null=True, blank=True)
    endereco = models.CharField(max_length=300, null=True, blank=True)
    numero = models.CharField(max_length=10, null=True, blank=True)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    bairro = models.CharField(max_length=300, null=True, blank=True)
    municipio = models.CharField(max_length=300, null=True, blank=True)
    uf = models.CharField(max_length=30, null=True, blank=True)
    dinheiro = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    pix = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    debito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    credito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fiado = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    frm_pg = models.CharField(max_length=30, null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True, default='aberto')

    objects = models.Manager()

    def __str__(self):
        return str(f' Pedido: {self.pk} Nome = {self.nome}')


    def get_pedido_url(self):
       return reverse_lazy("caixa:registradora_home", kwargs={"pk":self.pk})
    
    def get_ler_url(self):
       return reverse_lazy("pedido:ler_pedido", kwargs={"pk":self.pk})



class Item(models.Model):
    pedido = models.ForeignKey(Pedido,related_name='item_ped', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto_Model, related_name='item_prod', on_delete=models.CASCADE)
    qt = models.DecimalField(decimal_places=0, max_digits=4, null=True, blank=True)
    preco = models.DecimalField(decimal_places=2, max_digits=14, null=True, blank=True)
    observacao = models.TextField(null=True, blank=True)
    item_acrescimo = models.TextField(null=True, blank=True)

    objects = models.Manager()

    def __str__(self):
        return str(self.pk)


class Acrescimo(models.Model):
    item = models.ForeignKey(Item, related_name='arecimo', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto_Model, related_name='produto', on_delete=models.CASCADE)
    qt = models.DecimalField(decimal_places=0, max_digits=4, null=True, blank=True)
    preco = models.DecimalField(decimal_places=2, max_digits=14, null=True, blank=True)

    objects = models.Manager()

    def __str__(self):
        return str(self.pk)

app/caixa/forms.py
from urllib import request
from django import forms
from django.core.exceptions import ValidationError
from produto.models import *
from .models import Caixa

class CaixaForm(forms.ModelForm):
    data = forms.DateTimeField(
        label="Data",
       
    )

    descricao = forms.CharField(
        label='Descrição',
        max_length=200,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Pagamento ou entrada Referente a ...'}
        )
    )
    valor = forms.CharField(
        label='Valor',
        max_length=14,
        widget=forms.TextInput(
            attrs={'type': 'text','data-mask':'###.###.##0,00' ,'data-mask-reverse':'true','size':'14','class':'form-control mask-money','placeholder':'Digite apenas numeros','defalt':'0,00'},
        
        )
    )
    tipo = forms.CharField(
        label= 'Operação',
        widget= forms.Select(
            attrs={'type':'select','class':'form-control'},
            choices={
                ('e','Entrada'),
                ('s','Saida'),
            },
        )
    )


    class Meta:
        model = Caixa
        fields = "__all__"

app/caixa/templates/caixa/caixa_home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<!--{#% include 'base/alerta.html' with notificacao=notificacao %}-->
<div class="container" xmlns:currency="http://www.w3.org/1999/xhtml"><br/>
    <h1 class="text-center" >Registro de Entrada e Saida do Caixa</h1>
<form action="{% url 'caixa:caixa_add' %}" data-point="{% url 'caixa:caixa_add' %}"  method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-10">
                    {{form.descricao.label}}
                    {{form.descricao}}
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    {{form.valor.label}}
                    {{form.valor}}
                </div>
                <div class="col-md-3">
                    {{form.tipo.label}}
                    {{form.tipo}}
                </div>
                <div class="col-md-2">
                    <br/>
                    <input type="submit" class="btn btn-success btn-block" value="Registrar">
                </div>
                
            </div>
        </div>
        <div class="col-md-4 pull-right">
            <div class="money" style="color:green;">
                <h4><strong>Entrada <span class="pull-right">R$: {{ent|safe}}</span></strong></h4>
            </div>
            <div class="money" style="color:red;">
                <h4><strong>Saida <span class="pull-right">R$: {{sai|safe}}</span></strong></h4>
            </div>
            {%if saldo >= 0%}
            <div class="money" style="color:blue;">
                <h3><strong>Saldo <span class="pull-right">R$: {{saldo|safe}}</span></strong></h3>
            </div>
            {%else%}
            <div class="money" style="color:red;">
                <h3><strong>Saldo <span class="pull-right">R$: {{saldo|safe}}</span></strong></h3>
                    <h4>Saldo Negativo no Caixa</h4>
            </div>
            {%endif%}
        </div>

    </div>
   

</form>
</div>
<br/>
<div class="container">

    {% if lista.exists %}
    <table class="table table-striped">
        <thead>
            <h1 class="text-center">Movimento do Caixa</h1>
            <tr>
                {% comment %} <th>Código</th> {% endcomment %}
                <th>Data</th>
                <th>Descrição</th>
                <th class="text-center" >Valor</th>
                <th class="text-center">Tipo</th>
            </tr>
        </thead>
        <tbody>
         {% for object in lista %}   
            {% if object.tipo == "e" %}
                <tr style="color:green;">
                    <td>{{object.data}}</td>
                    <td>{{object.descricao|truncatewords_html:10|safe}}</td>
                    <td>R$ <span class="pull-right">{{object.valor}}</span></td>
                    <td class="text-center"> Entrada </td>
                </tr>
            {%else %}
                <tr style="color:red;">
                    {% comment %} <td>{{object.id}}</td> {% endcomment %}
                    <td>{{object.data}}</td>
                    <td>{{object.descricao}}</td>
                    <td>R$ <span class="pull-right">{{object.valor|safe}}</span></td>
                    <td class="text-center"> Saida </td>
                </tr>
            {% endif %}
         {% endfor %}
        </tbody>
    </table>
{% else %}    
    <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}    

</div>
<script>
        result = valor4.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'});
        document.getElementById('result').value=result;
</script>
{% endblock content %}
    

app/caixa/templates/caixa/fechar-mesa.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-group">
    <div class="row">
      <div class="col-md-4">
        <h1><strong class=" text-center">Mesa:</strong> {{mesa.numero}}</h1>
      </div>
      <div class="col-md-4 ">
        <h1><strong class="text-center">Total:</strong> {{mesa.total}} </h1>
      </div>    
      <div class="col-md-3">
        <h1><strong class="text-center">Total Ped:</strong> {{mesa.ped_mesa.count}} </h1>
      </div>
    </div>
</div>    
<div class="col-md-12" style="width: 100%; border-bottom: 1px solid #000000;" >
    
</div>
<br/>
<div class="col-md-12"  >
<div class="row"> 
    <div class="col-md-8">
        <div class="form-group">
            {% for item in mesa.ped_mesa.all %}
                <div class="col-md-12" >
                    <div class="row">
                        <div class="col-md-3"  >
                            <label class="text-leaft"><h5><strong>Pedido</strong>: {{item.id|safe}}</h5></label>
                        </div>
                        <div class="col-md-6">
                            
                            <label><p>{{item.pedido|safe}}</p></label>
                        </div>
                    </div>
                    <div class="col-md-6" style="width: 100%; border-bottom: 1px solid #000000; " >
                        <span class="text-center">
                           <h1> R$: {{item.total_pedido}}</h1>
                        </span>
                    </div>
                </div>
            <br/>
            {% endfor %}
        </div>
    </div> 
    <div class="col-md-4">
        {% comment %} <div class="row">
            <div style="width: 100%; border-bottom: 1px solid #000000; ">
                <a type="button" href="#" data-bs-toggle="modal" data-bs-target="#myModal"><i type='submit'  class="fa fa-print">&nbsp;Imprimir</i></a>
                &nbsp;&nbsp;&nbsp;
                <a type="button" href="#" data-bs-toggle="modal" data-bs-target="#myModal2"><i type='submit'  class="fa fa-truck">&nbsp;Entrega</i></a>
                &nbsp;&nbsp;&nbsp;
                <a type="button" href="{% url 'pedido:mesa_list' %}" ><i type='submit'  class="fa fa-table">&nbsp;Mesas & Pedidos</i></a>

            </div>
        </div> {% endcomment %}
        <div class="form-group">
            <form method='POST' action='{% url "caixa:registradora_pagamento_mesa" mesa.id %}' data-endpoint='{% url "caixa:registradora_pagamento" mesa.id %}' class="form">    
                {%csrf_token%}
                <br/>
                <div class="form-group">
                    <h3>Total: R$ <a href="#" name="totalvl" >{{mesa.total}}</a> </h3>
                        <input type="hidden"  name="totalvl" value="{{mesa.total}}"/>
                </div>
                <div class="form-group" style="width: 100%; border-bottom: 1px solid #000000;">
                    <div class="form-group">
                        <label>Dinheiro: <input type="text"  style="width:200px;"  name="dinheiro" data-mask="###.###.##0,00" data-mask-reverse="true" id="id_dinheiro" class="form-control" value="{{mesa.dinheiro}}" /></label>
                        <label>PIX: <input type="text" style="width:200px;"  name="pix" data-mask="###.###.##0,00" data-mask-reverse="true" id="id_pix" class="form-control" value="{{mesa.pix}}" /></label>
                    </div>
                    <div class="form-group">
                        <label>Cartão Debito: <input type="text" style="width:200px;" name="debito" data-mask="###.###.##0,00" data-mask-reverse="true" id="id_debito" class="form-control" value="{{mesa.debito}}" /></label>
                        <label>Cartão Credito: <input type="text" style="width:200px;"  name="credito" data-mask="###.###.##0,00" data-mask-reverse="true" id="id_credito" class="form-control" value="{{mesa.credito}}" /></label>
                    </div>
                    (tecle enter para adicionar os valores)
                    <button type="submit" class="btn btn-light "></button>
                </div>
                <div class="row">
                    <h3>Recebido: R$ <a style="color:green;" >{{recebido}}</a> </h3>
                </div>
                <div class="row">  
                    {% if faltante < 0%}
                    <h2>Falta: R$ <a style="color:red;">{{faltante|safe}}</a></h2>
                    {% endif%}
                    {% if faltante > 0%}
                    <h2>Troco: R$ <a style="color:green;">{{faltante|safe}}</a></h2>
                    {% endif%}
                </div>
                <input type="hidden" name="troco" value="{{faltante}}" >
                                        
            
            </form>
            {%if mesa %}
                {%if faltante >= 0 %}
                <form method='POST' name="entrega" action="{% url 'caixa:registradora_mesa_receber' mesa.id %}" data-endpoint="{% url 'caixa:registradora_mesa_receber' mesa.id %}">    
                    {%csrf_token%}
                    <button type="submit" class="btn btn-primary btn-block" data-bs-toggle="modal" data-bs-target="#myModal" >Finalizar Pedido</button>
                </form>
                {%endif%}
            {%endif%}
        </div>

    </div>
</div>
</div>
 

{%endblock%}

app/caixa/templates/caixa/list_mesa.html
{% extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{%block content%}

<div class="form-group">
    <div class="row">
        <div class="col-md-3">
            <div class="container" style="width: 100%; border-right: 1px solid #000000;">
                {{mes}}
                <div class="form-group">
                    <button type="button" class="btn btn-primary btn-block fa fa-plus" data-bs-toggle="modal" data-bs-target="#criar_mesa">
                        Mesa
                    </button>
                </div>
                <div class="form-group">
                    {% if mesa.exists %}
                        {% for m in mesa%}
                        <div class="card border-success mb-12" style="max-width: 15rem; max-height: 10rem;">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-md-10">
                                        <h5>Mesa: {{m.numero}}</h5>
                                    </div>
                                    <div class="col-md-2">
                                        {% if m.total == 0.00 %}
                                            <a href="{% url 'pedido:mesa_delete' m.id %}" >
                                                <i class="fa fa-close "></i>
                                            </a>
                                        {% endif %}    
                                    </div>
                                </div>
                            </div>
                            <div class="card-body text-success">
                                <a href="{{m.get_mesa_url}}" >
                                    <h5 class="card-title">R$: {{m.total}}</h5>
                                </a>
                            </div>
                        </div>
                        <br/>
                        {% endfor %}
                    {% else %}
                        <p class="alert alert-warning">Sem mesa na lista.</p>
                    {% endif %}
                
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="container" style="width: 100%; border-right: 1px solid #000000;">
                <div class="form-group">
                    <form method="POST" action="{% url 'pedido:pedido_criar' %}" data-endpoint="{% url 'pedido:pedido_criar' %}">
                        {% csrf_token%}
                        <a type="submit" href="{%url 'pedido:pedido_criar'%}"  class="btn btn-primary  btn-block fa fa-plus"> Pedido</a>
                    </form>
                </div>
                <div class="form-group">
                    {% if pedido.exists %}
                        {% for m in pedido%}
                            <div class="card border-success mb-12" style="max-width: 15rem; max-height: 10rem;">
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-md-10">
                                            <h5>Pedido: {{m.id}}</h5>
                                        </div>
                                        <div class="col-md-2">
                                            <a href="{% url 'pedido:pedido_delete' m.id %}" >
                                                <i class="fa fa-close "></i>
                                            </a>    
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body text-success">
                                    <a href="{{m.get_pedido_url}}" >
                                        <h5 class="card-title">{{m.total_pedido}}</h5>
                                        <p class="card-text">{{m.venda}}</p>
                                    </a>
                                </div>
                            </div>
                            <br/>
                        {% endfor %}
                    {% else %}
                        <p class="alert alert-warning">Sem pedido na lista.</p>
                    {% endif %}
                </div>

            </div>
        </div>
        <div class="col-md-6">
            {% include 'caixa/registradora_list.html' with enviado=enviado pedido=pedido recebido=recebido entrega=entrega finalizado=finalizado %}
        </div>

    </div>

</div>

<form method="POST" action="{% url 'pedido:mesa_criar' %}" data-endpoint="{% url 'pedido:mesa_criar' %}">
    {% csrf_token %}
    <div class="modal fade" id="criar_mesa" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="criar_mesaLabel">N° Mesa :</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name='mesa' id="id_mesa" class="form-control" />
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Abrir Mesa</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{%endblock%}