app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('loja/', include('loja.urls', namespace='loja')),
    path('produto/', include('produto.urls', namespace='produto')),
    path('estoque/', include('estoque.urls', namespace='estoque')),
    path('caixa/', include('caixa.urls', namespace='caixa')),
    path('pedido/', include('pedido.urls', namespace='pedido')),
]
urlpatterns += [path("accounts", include("django.contrib.auth.urls"))]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/estoque/urls.py
from django.urls import path
from .views import *

app_name = 'estoque'

urlpatterns = [
    path('', estoque_lista, name='estoque_list'),
    path("<int:pk>detail/", Estoque_Detalhe.as_view(), name="estoque_detail"),
    path('move/', estoque_movimento, name='estoque_move'),
    path('abrir/', nota_abrir, name='nota_abrir'),
    path('<int:pk>item/', adcionar_item, name='estoque_add'),
    path('item_del', excluir_item, name='excluir_item'),
    path('nota/', gerar_nota, name='gerar_nota'),
    path('delete/', excluir_nota, name='excluir_nota'),
]

app/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from produto.models import Produto_Model
from loja.models import Loja_Model

# Create your models here.
    
class Und_Medida(models.Model):
    nome = models.CharField(max_length=30, null=True, blank=True)
    
    def __str__(self):
        return self.nome
    

class Fornecedor_Model(models.Model):
    loja = models.ForeignKey(Loja_Model, related_name='fornecedor', on_delete=models.CASCADE)
    nome = models.CharField(max_length=30, null=True)
    cnpj = models.CharField(max_length=200, unique=True, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True)
    cep = models.CharField(max_length=30, null=True)
    endereco = models.CharField(max_length=300, null=True)
    numero = models.CharField(max_length=10, null=True)
    complemento = models.CharField(max_length=100, null=True)
    bairro = models.CharField(max_length=300, null=True)
    municipio = models.CharField(max_length=300, null=True)
    UF = models.CharField(max_length=30, null=True)
    objects = models.Manager()

    def __str__(self):
        return self.nome
    


MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)

class Nota_Model(models.Model):
    loja = models.ForeignKey(Loja_Model, related_name='nota', on_delete=models.CASCADE)
    #fornecedor =models.ForeignKey(Fornecedor_Model, on_delete=models.CASCADE)
    nf = models.CharField('Nota Fiscal', max_length=10, null=True, blank=True)
    dia = models.CharField(max_length=10, null=True, blank=True)
    movimento = models.CharField(choices=MOVIMENTO, max_length=1)
    total = models.CharField(max_length=10, null=True, blank=True)
    status = models.CharField(max_length=10, null=True,blank=True, default='aberto')
    objects = models.Manager()

    def __str__(self):
        return self.nf

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_detail', kwargs={'pk': self.pk})

    

class Item_Model(models.Model):
    loja = models.ForeignKey(Loja_Model, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto_Model, on_delete=models.CASCADE)
    nota = models.ForeignKey(Nota_Model, related_name='item',on_delete=models.CASCADE)
    data_validade = models.CharField(max_length=30, null=True)
    ncm = models.CharField(max_length=50, null=True, blank=True)
    unidade = models.ForeignKey(Und_Medida, on_delete=models.PROTECT,null=True, blank=True)
    quantidade = models.IntegerField( null=True, blank=True)
    preco_unid = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    preco = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    objects = models.Manager()

    def __str__(self):
        #return f'{self.pk} {self.nota} {self.produto}'
        return f'{self.pk}'
    
    

app/estoque/forms.py
from urllib import request
from django import forms
from django.contrib.auth.models import User
from django.shortcuts import render
from .models import *




class Fornecedor_Form(forms.ModelForm):
    nome = forms.CharField(
        label='Nome Fantasia',
        max_length=150,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control',
                   'placeholder': 'Digite o nome fantasia da loja'}
        )
    )
    responsavel = forms.CharField(
        label='Razão Social',
        max_length=150,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control',
                   'placeholder': 'Digite o nome fantasia da loja'}
        )
    )
    cnpj = forms.CharField(
        label='CNPJ',
        max_length=18,
        widget=forms.TextInput(
            attrs={'type': 'text', 'data-mask': '00.000.000/0000-00', 'class': 'form-control mask-cnpj',
                   'placeholder': 'Digite apenas Numeros', 'required': 'False'}
        )
    )
    cpf = forms.CharField(
        label='CPF',
        max_length=14,
        widget=forms.TextInput(
            attrs={'type': 'text', 'data-mask': '000.000.000-00', 'class': 'form-control mask-cpf',
                   'placeholder': 'Digite apenas Numeros', 'required': 'False'}
        )
    )
    telefone = forms.CharField(
        label='Celular',
        max_length=16,
        widget=forms.TextInput(
            attrs={'type': 'text', 'data-mask': '(00) 0 0000-0000',
                   'class': 'form-control', 'placeholder': 'Digite apenas Numeros'}
        )
    )
    cep = forms.CharField(
        label='CEP',
        max_length=10,
        widget=forms.TextInput(
            attrs={'type': 'text', 'id': 'id_cep', 'data-mask': '00000-000',
                   'class': 'form-control', 'placeholder': '12345-000', }
        )
    )
    endereco = forms.CharField(
        label='Rua, Av, etc',
        max_length=150,
        widget=forms.TextInput(
            attrs={'type': 'text', 'id': 'id_endereco',
                   'class': 'form-control', 'placeholder': 'Endereco do Bar'}
        )
    )
    numero = forms.CharField(
        label='Numero',
        max_length=10,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control',
                   'placeholder': 'Numero'}
        )
    )
    complemento = forms.CharField(
        label='Complemento',
        max_length=150,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control',
                   'value': 'Sem Complemento'}
        )
    )
    bairro = forms.CharField(
        label='Bairro',
        max_length=150,
        widget=forms.TextInput(
            attrs={'type': 'text', 'id': 'id_bairro',
                   'class': 'form-control', 'placeholder': 'Bairro'}
        )
    )
    municipio = forms.CharField(
        label='Municipio',
        max_length=150,
        widget=forms.TextInput(
            attrs={'type': 'text', 'id': 'id_municipio',
                   'class': 'form-control', 'placeholder': 'Cidade'}
        )
    )
    UF = forms.CharField(
        label='UF',
        max_length=2,
        widget=forms.TextInput(
            attrs={'type': 'text', 'id': 'id_UF',
                   'class': 'form-control', 'placeholder': 'Estado'}
        )
    )

    class Meta:
        model = Fornecedor_Model
        fields = '__all__'

class Nota_Form(forms.ModelForm):
    
    dia = forms.CharField(
        label='Data Nota:',
        max_length=10,
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'form-control',
                   'placeholder': 'Data da Nota'},

        )
    )

    nf = forms.CharField(
        label='Nota Fiscal:',
        max_length=10,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control',
                   'placeholder': 'Numero da Nota'},

        )
    )
    movimento = forms.CharField(
        label='Movimento:',
        max_length=7,
        widget=forms.Select(
            attrs={'type': 'select', 'class': 'form-control'},
            choices={
                ('e', 'Entrada'),
                ('s', 'Saida'),
            },
        )
    )
    # total = forms.CharField(
    #     label='Valor Total da Nota ',
    #     max_length=14,
    #     widget=forms.TextInput(
    #         attrs={'type': 'decimal/text', 'data-mask': '#####0.00', 'data-mask-reverse': 'true',
    #                'class': 'form-control mask-money', 'placeholder': '0,00'},
    #     )
    # )

    class Meta:
        model = Nota_Model
        fields = [
            #'fornecedor',
            'nf',
            'dia',
            'movimento',
            # 'total',
        ]

class Item_Form(forms.ModelForm):
    
  
    quantidade = forms.CharField(
        label='QT:',
        max_length=7,
        widget=forms.TextInput(
            attrs={'type': 'number/text', 'class': 'form-control', 'data-mask': '####00',
                   'data-mask-reverse': 'true', 'class': 'form-control mask-money', 'onfocus':'calcular()', 'placeholder': 'Quantidade'},

        )
    )
    preco_unid = forms.CharField(
        label='Vl Unid',
        max_length=14,
        widget=forms.TextInput(
            attrs={'type': 'decimal/text', 'maxlength': '14', 'data-mask': '########0.00',
                   'data-mask-reverse': 'true', 'class': 'form-control mask-money', 'onblur':'calcular()', 'placeholder': '0,00'},
        )
    )
    preco = forms.CharField(
        label='Vl Total',
        widget=forms.TextInput(
            attrs={'type': 'decimal/text', 'data-mask': '########0.00', 'maxlength': '14',
                   'data-mask-reverse': 'true', 'class': 'form-control mask-money', 'placeholder': '0,00'},
        )
    )
    data_validade = forms.CharField(
        label='Data de Validade',
        max_length=10,
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'form-control'},

        )
    )
    ncm = forms.CharField(
        label='NCM',
        max_length=8,
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control', 'maxlength': '8',
                   'data-mask': '######000', 'data-mask-reverse': 'true', 'placeholder': 'Quantidade'},

        )
    )
    
    class Meta:
        model = Item_Model
        fields = [
            'data_validade',
            'ncm',
            'unidade',
            'quantidade',
            'preco_unid',
            'preco',
        ]
    

app/estoque/views.py
from decimal import Decimal
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib import messages
from caixa.models import Caixa
from produto.models import Produto_Model
from .models import Nota_Model
from .forms import *

def estoque_lista(request):
    template_name = "estoque/estoque_list.html"
    object = Nota_Model.objects.filter(loja=request.user.loja, status="fechada")
    context=dict(
        object_list=object
    )
    return render(request, template_name, context)

class Estoque_Detalhe(DetailView):
    template_name = 'estoque/estoque_detail.html'
    model = Nota_Model
    context_object_name = 'nota'

def estoque_movimento(request):
    template_name = "estoque/estoque_form.html"
    nota = Nota_Model.objects.filter(status="aberto", loja=request.user.loja)
    if nota.exists():
        nota = Nota_Model.objects.get(status="aberto", loja=request.user.loja)
       
        return redirect('estoque:estoque_add', pk = nota.id)
    else:
        return redirect('estoque:nota_abrir')
       
    return render(request, template_name, context)

def nota_abrir(request):
    template_name = "estoque/estoque_form.html"
    form1 =  Nota_Form(request.POST or None)
    context={
        'form1':form1,
        'titulo': "Gerar Nota",
        'botao': "Gerar",
    }
    if request.method == "POST":
        form1 =  Nota_Form(request.POST or None)
        if form1.is_valid():
            print('É valido')
            prod = form1.save(commit=False)
            prod.loja=request.user.loja
            prod.save()
           
            messages.success(request, 'Nota Foi cadastrado com sucesso!')
            return redirect('estoque:estoque_move')
        else:
            print('Não é valido')
            messages.error(request, 'Erro ao cadastrar produto.')
        
        context={
            'form1':form1,
            'titulo': "Configurar Usuario",
            'botao': "Salvar",
        }
        
    return render(request, template_name, context)

def adcionar_item(request,pk):
    template_name = "estoque/estoque_form.html"  
    nota = Nota_Model.objects.get(id = pk)
    item = Item_Model.objects.filter(nota=nota, loja=request.user.loja)
    produto = Produto_Model.objects.filter(loja=request.user.loja)
    form = Item_Form(request.POST or None)
    context=dict(
        form=form,
        nota=nota,
        item=item,
        produto = produto,
    )
    if request.method == "POST":
        form =  Item_Form(request.POST or None)
        if form.is_valid():
            print('É valido')
            produto = Produto_Model.objects.get(id=request.POST.get('prod'))
            f = form.save(commit=False)
            f.produto= produto
            f.nota = nota
            f.loja = request.user.loja
            f.save()
                
            messages.success(request, 'Item adcionado com sucesso!')
            return redirect('estoque:estoque_move')
        

        else:
            
            print('Não é valido')
            messages.error(request, 'Erro ao cadastrar produto.')
            context=dict(
                form=form,
                nota=nota,
            )
       
    return render(request, template_name, context)

def gerar_nota(request):

    nf_id = request.POST.get('nota_id')
    nota = Nota_Model.objects.get(id=nf_id)
    item = Item_Model.objects.filter(nota=nota.id)

    vl=0
    for n in item:
        vl+= Decimal(n.preco)

    nota.total = vl
    nota.status = "fechada"
    nota.save()
    print(nota.id)

    if nota.movimento == "e":
        for i in item:
            produto=Produto_Model.objects.get(nome = i.produto)
            produto.estoque += Decimal(i.quantidade)
            produto.data_validade = i.data_validade
            produto.preco_compra = Decimal(i.preco_unid)
            if produto.preco == 0.00:
                vl = Decimal(i.preco_unid)
                produto.preco = vl*(vl*Decimal(99/100)+vl)
            produto.ativo = True
            produto.save()

            caixa = Caixa.objects.create(
                loja=request.user.loja,
                tipo= "s",
                descricao=f"Nota compra n°:{nota.nf}",
                valor=nota.total,
            )
            caixa.save()

    else:
        for i in item:
            produto=Produto_Model.objects.get(nome = i.produto)
            produto.estoque -= Decimal(i.quantidade)
            if produto.estoque <= 0:
                produto.ativo = False
            produto.save()  

            caixa = Caixa.objects.create(
                loja=request.user.loja,
                tipo= "e",
                descricao=f"Nota venda n°:{nota.nf}",
                valor=nota.total,
            )
            caixa.save()


    return redirect("estoque:estoque_list")

def excluir_nota(request):
    nf_id = request.POST.get('delete_id')
    nota = Nota_Model.objects.get(id=nf_id, loja=request.user.loja)
    nota.delete()

    print(f" excluido {nota.id}")

    return redirect("estoque:estoque_list")    

def excluir_item(request):
    nf_id = request.POST.get('item_id')
    item = Item_Model.objects.get(id=nf_id, loja=request.user.loja)
    item.delete()

    return redirect("estoque:estoque_move")   

app/estoque/templates/estoque/abrir_nota.html
<div class="row">
    <div class="col-sm-5">
        {{form.produto|as_crispy_field}}
    </div>
    <div class="col-sm-3">
        {{form.data_validade|as_crispy_field}}
    </div>
    
    <div class="col-sm-2">
        {{form.ncm|as_crispy_field}}
    </div>
</div>
<div class="row" >
    <div class="col-sm-2">
        {{form.unidade|as_crispy_field}}
    </div>
    <div class="col-sm-2">
        {{form.quantidade|as_crispy_field}}
    </div>
    <div class="col-sm-2">             
        {{form.preco_unid|as_crispy_field}}
    </div>
    <div class="col-sm-2">    
        {{form.preco|as_crispy_field}}
    </div>
   
</div>

app/estoque/templates/estoque/add_item.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% block css %}
<style>
    span.required::after{
        content:'*';
        color:red;
    }
 
</style>
{% endblock css %}
<div class="col-md-12">
    <div class="row">
        {% if nota.status == "aberto" %}
        <div class="col-md-2">    
            {%include 'estoque/gerar_nota.html' with nota=nota %}
        </div>
        <div class="col-md-2">
            <span class='pull-left'>
                {%include 'estoque/estoque_delete.html' with delete=nota %}
            </span>    
        </div>
        {% endif %}
    </div>
    <span class='pull-right'>
        <a href="{% url 'estoque:estoque_list' %}" class="btn btn-danger"  >
            <i class="fa fa-times"></i>
        </a>
    </span>
</div>
<div class="container">
    <div class="text-center">
        <h3><strong>Movimento do Estoque</strong></h3>
    </div>
    <br/>
    <div class="form-group">
        <div class="row">
            <div class="col-md-2" style="border-right: 1px solid; color:black;">
                
                    <label for="id_nf" class="form-label requiredField">
                        Nota Fiscal:<span class="asteriskField">*</span> 
                        <h3>{{nota.nf}}</h3>
                    </label>        
                    <label for="id_dia" class="form-label requiredField">
                        Data Nota:<span class="asteriskField">*</span> 
                        <h3>{{nota.dia}}</h3>
                    </label> 
                    <label for="id_movimento" class="form-label requiredField">
                        Movimento:<span class="asteriskField">*</span>
                        {% if nota.movimento == "e" %}
                            <h3>Entrada</h3>
                        {% else %}
                        <h3>Saida</h3>
                        {% endif %}
                            
                    </label>    
                    <label for="id_total" class="form-label requiredField">
                        Valor Total da Nota <span class="asteriskField">*</span> 
                        <input type="hidden" name="total"  data-mask="###. ###.000,00" data-mask-reverse="true" class="form-control mask-money textinput" placeholder="0,00" maxlength="14" required id="id_total" value=" {% if nota.total %} {{nota.total}} {% else %} 000 {% endif %} " />
                        <h3>
                            <span data-mask="###. ###.000,00" data-mask-reverse="true" class="mask-money">
                                {{nota.total}}
                            </span> 
                        </h3>   
                    </label>
                                    
                    <form method="POST" action="{% url 'estoque:nota_abrir' %}"  class="form-group" novalidate>
                        {% csrf_token %}
                        {{form1|crispy}} 
                        <div class="col-sm-12" style="margin-top: 30px;" >
                            <div class="form-inline button">
                                <button type="submit" class="btn btn-primary" value="Adicionar">
                                    <i class="fa fa-floppy-o">
                                        {% autoescape off %}
                                        {{iconeI}}
                                        {% endautoescape %}
                                        {{botaoI}}
                                    </i>
                                </button>
                            </div>
                        </div>    
                    </form>
            </div>
            <div class="col-md-10">    
                <div class="form-group">
                    <form method="POST" name='estoque/add_item.html' action="{% url 'estoque:estoque_add' %}"  class="form-group" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="nota_id" value="{{nota.id}}"/>
                        {{form.on_field_errors}}
                        <div class="row">
                            <div class="col-sm-5">
                                {{form.produto|as_crispy_field}}
                            </div>
                            <div class="col-sm-3">
                                {{form.data_validade|as_crispy_field}}
                            </div>
                            
                            <div class="col-sm-2">
                                {{form.ncm|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row" >
                            <div class="col-sm-2">
                                {{form.unidade|as_crispy_field}}
                            </div>
                            <div class="col-sm-2">
                                {{form.quantidade|as_crispy_field}}
                            </div>
                            <div class="col-sm-2">             
                                {{form.preco_unid|as_crispy_field}}
                            </div>
                            <div class="col-sm-2">    
                                {{form.preco|as_crispy_field}}
                            </div>
                            <div class="col-sm-2">
                                <div class="row float-right">
                                    <div class="col-sm-12" style="margin-top: 30px;" >
                                        <div class="form-inline button">
                                            <button type="submit" class="btn btn-primary" value="Adicionar">
                                                <i class="fa fa-floppy-o">
                                                    {% autoescape off %}
                                                    {{iconeI}}
                                                    {% endautoescape %}
                                                    {{botaoI}}
                                                </i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>        
                </div>   
            </div>
        </div>   
    </div>
</div>
<script>
    function calcular(){
        var valor1 = parseFloat(document.getElementById('id_quantidade').value, 10);
        var valor2 = parseFloat(document.getElementById('id_preco_unid').value, 10);
        var result = valor1*valor2;
        var result2 = result.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'})
        var result3 = result2.replace("R$","").replace(".","").replace(",",".")
        document.getElementById('id_preco').value=result3;
    }
    {% comment %} <input id="txt1" type="text" value="1" onfocus="calcular()"/> {% endcomment %}
    {% comment %} <input id="txt2" type="text" value="1" onblur="calcular()"/> {% endcomment %}
    {% comment %} <input id="result" type="text"/> {% endcomment %}
    {% comment %} var valor3 = valor2.replace(".","").replace(",","."); {% endcomment %}
        {% comment %} console.log(valor3); {% endcomment %}
        {% comment %} var valor4 = valor1 * parseFloat(valor3); {% endcomment %}
        {% comment %} result = valor4.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}); {% endcomment %}
</script>
    

{% endblock content %}

app/estoque/templates/estoque/delete_item.html
<form method="POST" action="{%url 'estoque:excluir_item' %}" class="form" >
    {%csrf_token%}
    <input type="hidden" name="item_id"  value="{{item.id}}"/>
    <button type="submit" class="btn btn-danger" >
        <i class="fa fa-trash-o">
           
        </i>
    </button>
</form>

app/estoque/templates/estoque/estoque_delete.html
<form method="POST" action="{%url 'estoque:excluir_nota' %}" class="form" >
    {%csrf_token%}
    <input type="hidden" name="delete_id"  value="{{delete.id}}"/>
    <button type="submit" class="btn btn-danger" >
        <i class="fa fa-trash-o">
            Excluir...?
        </i>
    </button>
</form>

app/estoque/templates/estoque/estoque_detail.html
{% extends 'base.html'  %}
{% block content %}
{% comment %} {% include 'loja/base/alerta.html' with notificacao=notificacao %} {% endcomment %}
<div class="container">
    <a href="{% url 'estoque:estoque_list' %}"></a>
    <h2>{{object}}</h2>
    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right"> Total da NF</th>
                    <td>{{object.total}}                </td>
                </tr>
                <tr>
                    <th class="text-right">Data</th>
                    <td>{{object.dia|safe}}</td>
                    
                </tr>
                <tr>
                    <th class="text-right">Movimento</th>
                    <td>
                        {%if object.movimento == "e"%}
                           <p style="color:green;" >Entrada</p>
                         {% else%}  
                         <p style="color:green;" >Saida</p>
                        {%endif%} 
                        
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <table class="table table-striped">
        <thead>
            <tr class="text-right" >
                <th class="text-center">Produtos</th>
                <th>Quantidade</th>
                <th> NCM</th>
                <th>Validade</th>
                <th class="text-right" >Vl Unitario</th>
                <th class="text-right" >Valor Total</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in nota.item.all%}
            <tr class="text-right">
            <td class="text-left" ><a href="{{obj.produto.get_absolute_url}}">{{obj.produto}}</a></td>
            <td class="text-right">{{obj.quantidade}}</td>
            <td>{{obj.ncm}}</td>
            <td>{{obj.data_validade}}</td>
            <td class="text-right">{{obj.preco_unid}}</td>
            <td class="text-right" >{{obj.preco}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content%}

app/estoque/templates/estoque/estoque_list.html
{% extends 'base.html'  %}

{% block content %}
<div class="container">
    <h2>Movimento do Estoque
        <span class="pull-right">
            
            <a href="{% url 'estoque:estoque_move'%}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span>
                    Adicionar
                </button>
            </a>
        </span>
    </h2>

    
    {% if object_list.exists %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>NF</th>
                    <th>Data</th>
                    <th>Movimento</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>
                            <a href="{{object.get_absolute_url}}">{{object}}</a>
                        </td>
                        <td>{{object.nf}}</td>
                        <td>{{object.dia|safe}}</td>
                        <td>
                            {%if object.movimento == "e"%}
                                <p style="color:green;" >Entrada</p>
                            {% else%}  
                                <p style="color:red;" >Saida</p>
                            {%endif%} 
 
                        </td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
    {% else %}    
        <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}    
</div>
{% endblock content%}

app/estoque/templates/estoque/gerar_nota.html
<form method="POST" action="{%url 'estoque:gerar_nota' %}" class="form" >
    {%csrf_token%}
    <input type="hidden" name="nota_id"  value="{{nota.id}}"/>
    <button type="submit" class="btn btn-success" >
        <i class="fa fa-floppy-o">
            Gerar Nota !
        </i>
    </button>
</form>