app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('loja/', include('loja.urls', namespace='loja')),
    path('produto/', include('produto.urls', namespace='produto')),
    path('estoque/', include('estoque.urls', namespace='estoque')),
    path('caixa/', include('caixa.urls', namespace='caixa')),
    path('pedido/', include('pedido.urls', namespace='pedido')),
]
urlpatterns += [path("accounts", include("django.contrib.auth.urls"))]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/caixa/urls.py
from django.urls import path
from .views import *

app_name = "caixa"


urlpatterns = [
    path('', caixa_home, name='caixa_home'),
    path('registra', caixa_add, name='caixa_add'),
    path('registradora-<int:pk>/', registradora_home, name='registradora_home'),
    path('<int:pk>/item', registradora_item, name='registradora_Item'),
    path('busca-<int:pk>', busca_produto, name='query'),
    path('obs', observacao, name='observacao'),
    path('delete', registradora_remover_item, name='registradora_remove'),
    path('acres', registradora_acrecimo, name='registradora_acrescimo'),
    path('<int:pk>/acrescimo_list', acrescimo_list, name='acrescimo_list'),
    path('<int:pk>/enviado', registradora_pedido, name='registradora_pedido'),
    path('<int:pk>/entrega', registradora_entrega, name='registradora_entrega'),
    path('<int:pk>/pagamento', registradora_pagamento, name='registradora_pagamento'),
    path('<int:pk>/enviado_pedido', registradora_aceitar_pedido, name='registradora_aceitar_pedido'),
    path('<int:pk>/balcao', registradora_retirar_balcao, name='registradora_retirar_balcao'),
    path('<int:pk>/mesa', registradora_retirar_mesa, name='registradora_retirar_mesa'),
    path('<int:pk>/fecharmesa', fechar_mesa, name='fechar_mesa'),
    path('<int:pk>/pagamento_mesa', registradora_pagamento_mesa, name='registradora_pagamento_mesa'),
    path('<int:pk>/fechado', registradora_mesa_receber, name="registradora_mesa_receber"),

]

app/estoque/urls.py
from django.urls import path
from .views import *

app_name = 'estoque'

urlpatterns = [
    path('', estoque_lista, name='estoque_list'),
    path("<int:pk>detail/", Estoque_Detalhe.as_view(), name="estoque_detail"),
    path('move/', estoque_movimento, name='estoque_move'),
    path('abrir/', nota_abrir, name='nota_abrir'),
    path('<int:pk>item/', adcionar_item, name='estoque_add'),
    path('item_del', excluir_item, name='excluir_item'),
    path('nota/', gerar_nota, name='gerar_nota'),
    path('delete/', excluir_nota, name='excluir_nota'),
]

app/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'


urlpatterns = [
    path('', home_page, name='home_page'),
    path('about/', about_page, name='sobre'),
    path('aboutl/', loja_about_page, name='loja_sobre'),
    path('contact/', contact_page, name='contato'),
    path('contactl/', loja_contact_page, name='loja_contato'),
]

app/loja/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import *
from .views import *

app_name = "loja"

urlpatterns = [
    path('', loja_home, name='loja_home'),
    path('loja/', Loja_Update.as_view(), name='loja_update'),
    # path('loja/', gerarLoja, name='loja_update'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('usuario:login')), name='logout'),
    path('registrar/', gerarUsuario, name='user-create'),
    path('update/', gerarPerfil, name='user-update'),

]

app/produto/urls.py
from django.urls import path
from .views import Produto_Detalhe, produto_list, adicionar_Produto,editar_produto,Produto_Delete


app_name="produto"

urlpatterns = [
    path("", produto_list, name="produto_list"),
    path("create/", adicionar_Produto, name="produto_add"),
    path("<int:pk>detail/", Produto_Detalhe.as_view(), name="produto_detail"),
    path("<int:pk>edit/", editar_produto, name="produto_edit"),
    path("<int:pk>delet/", Produto_Delete.as_view(), name="produto_delete")
]

app/home/models.py
from django.db import models

# Create your models here.
class Pag_Contato(models.Model):
    nome = models.CharField(max_length=300)
    email = models.EmailField(max_length=300)
    mensagem = models.TextField()
    objects = models.Manager()

    def __str__(self):
        return self.nome
    

class Texto(models.Model):
    titulo = models.CharField(max_length=100)
    texto = models.TextField(max_length=500)
    image = models.ImageField(upload_to='text_image/',  blank=True, null=True)

    def __str__(self):
        return self.titulo
    

app/home/forms.py
from django import forms
from.models import Pag_Contato


class ContactForm(forms.Form):
    nome_completo = forms.CharField(
    error_messages={'required': 'Obrigatório o preenchimento do nome'},
        widget=forms.TextInput(
            attrs={
                    "class": "form-control",
                    "placeholder": "Seu nome completo"
                }
            )
        )
    email= forms.EmailField(
        error_messages={'invalid': 'Digite um email válido!'},
        widget=forms.EmailInput(
            attrs={
                    "class": "form-control",
                    "placeholder": "Digite seu email"
                }
            )
        )
    mensagem= forms.CharField(
        error_messages={'required': 'É obrigatório o preenchimento do campo mensagem!'},
        widget=forms.Textarea(
            attrs={
                    "class": "form-control",
                    "placeholder": "Digite sua mensagem"
                }
            )
)
    class Meta:
        model = Pag_Contato
        fields = "__all__"

app/home/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import ContactForm
from .models import Pag_Contato, Texto


# Create your views here.

def home_page(request):
    tela = "home/index.html"
    texto = Texto.objects.all()

    context = dict(
        texto=texto
    )

    return render(request, tela, context)


def about_page(request):
    tela = "home/view.html"
    context = {
        'title': "Kinquilharias RCM",
        'titulo': "Sobre",
        'comentario': "Um pouco sobre nós",
    }
    return render(request, tela, context)


def contact_page(request):
    tela = "home/view.html"
    form = ContactForm(request.POST or None)
    context = {
        'title': "Kinquilharias RCM",
        'titulo': "Contato",
        'comentario': "Deixe aqui suas criticas, comentarios e sujestões ou duvidas",
        'form': form,
    }

    if form.is_valid():
        contato = Pag_Contato(
            nome=request.POST.get("nome_completo"),
            email=request.POST.get("email"),
            mensagem=request.POST.get("mensagem"),

        )
        contato.save()
        context = {
            'title':"Contact Page",
            'comentario':"Mensagem enviada com sucesso",
        }
        return render(request, tela, context)
    return render(request, tela, context)

def loja_about_page(request):
    tela="base/view2.html"    
    context = {
        'title': "Kinquilharias RCM",
        'titulo': "Sobre",
        'comentario': "Um pouco sobre nós",
    }
    return render(request, tela, context)


def loja_contact_page(request):
    tela="base/view2.html"    
    form = ContactForm(request.POST or None)
    context = {
        'title': "Kinquilharias RCM",
        'titulo': "Contato",
        'comentario': "Deixe aqui suas criticas, comentarios e sujestões ou duvidas",
        'form': form,
    }

    if form.is_valid():
        contato = Pag_Contato(
            nome=request.POST.get("nome_completo"),
            email=request.POST.get("email"),
            mensagem=request.POST.get("mensagem"),

        )
        contato.save()
        context = {
            'title':"Contact Page",
            'comentario':"Mensagem enviada com sucesso",
        }
        return render(request, tela, context)
    return render(request, tela, context)

app/home/templates/base/alerta.html
  <form action="." method="POST">
    {% csrf_token%}
    {{notificacao.id}}
    {% if notificacao %}
      <div id="id_do_elemento" class=" col-md-6  alert alert-warning" role="alert">
        <a href="{% url 'produto:pedido_list' %}"><h1>Atenção PEDIDO CHEGANDO</h1></a>
            
      </div>
    {% endif %}
  </form>

app/home/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.6.3/jquery-confirm.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
<!--Font Awesome CSS-->
<link href="/docs/4.1/assets/css/docs.min.css" rel="stylesheet">
<link href="/docs/4.1/dist/css/bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="app/static_local/Js/jquery-3.6.3.min.js">
<!--jquery-confirm css-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/css/bootstrap.min.css" integrity="sha512-6KY5s6UI5J7SVYuZB4S/CZMyPylqyyNZco376NM2Z8Sb8OxEdp02e1jkKk/wZxIEmjQ6DRCEBhni+gpr9c4tvA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

app/home/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS  and jquery-confirm JS-->
<script src="{% static '/Js/js.js' %}" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS  and jquery-confirm JS-->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="{% static '/Js/js.js' %}" ></script>
<script src="{% static '/Js/popper.min.js' %}" ></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="js/jsquery-3.63.min.js"></script>
<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<link rel="stylesheet" href="app/static_local/Js/jquery-3.6.3.min.js">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-ewfXo9Gq53e1q1+WDTjaHAGZ8UvCWq0eXONhwDuIoaH8xz2r96uoAYaQCm1oQhnBfRXrvJztNXFsTloJfgbL5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

app/home/templates/base/navbar.html
{% load static %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid"><input type="hidden" name="loja_id" value="{{loja.id}}">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav"  aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="main_nav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'loja:loja_home' %}" >Home<span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'loja:user-update'%}">Perfil<span class="sr-only"></span></a>
          </li>
          {% if  user.perfil.cpf %}
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'loja:loja_update' %}" >Loja<span class="sr-only"></span></a>
          </li>
         {%endif%}
          {%if request.user.loja.loja%}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'produto:produto_list' %}">Produto <span class="sr-only"></span></a>
          </li>
          {% comment %} <li class="nav-item active">
            <a class="nav-link" href="{#% url 'produto:pedido_list' %}">Pedido <span class="sr-only"></span></a>
          </li> {% endcomment %}
          <li class="nav-item active">
            <a class="nav-link " href="{% url 'estoque:estoque_list' %}" > Estoque <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'caixa:caixa_home' %}"> Movimento do Caixa </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'caixa:registradora_home' 1 %}"> Frente de Caixa </a>
          </li>
          {%endif%}
        </ul>
      </div>
        <div class="container-pull-right">
          <span class="nav-item active">
            User: {{ user.get_username }}<a href="{% url 'logout'%}"> Sair</a>
          </span>
        </div>
    <!-- navbar-collapse.// -->
    </div>
    <!-- container-fluid.// -->
  </nav>
<br/><br/><br/>

app/home/templates/base/rodape2.html
{% load static %}

<div class="my-3 pt-5 text-muted text-center text-small">

    <ul class="list-inline">
        <li class="list-inline-item"><a href="{% url 'home:loja_sobre' %}">Sobre</a></li>
        <li class="list-inline-item"><a href="#">Privacidade</a></li>
        <li class="list-inline-item"><a href="#">Termos</a></li>
        <li class="list-inline-item"><a href="{% url 'home:loja_contato' %}">Contato</a></li>
    </ul>
     <p class="mb-1">&copy; {% now "Y" %} by Kinquilharias R C M</p>
</div>

app/home/templates/base/view2.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class='text-center'>
        <h1>{{ title }}</h1>
    </div>
    <div class='container'>
        <div class='row'>

            <div class='col'>
                <div class='col-sm-6 col-12'>
                    {% if form %}
                    <h3>{{ comentario}}</h3>
                    <form method='POST'>
                        {% csrf_token %}
                        {{ form | crispy }}
                        <br>
                        <div class="text-center">
                            <button type='submit'  class=' btn btn-primary'> Enviar   </button>
                        </div>
                    </form>
                    {% else %}
                    <h3>{{ comentario }}</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}