app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('loja/', include('loja.urls', namespace='loja')),
    path('produto/', include('produto.urls', namespace='produto')),
    path('estoque/', include('estoque.urls', namespace='estoque')),
    path('caixa/', include('caixa.urls', namespace='caixa')),
    path('pedido/', include('pedido.urls', namespace='pedido')),
]
urlpatterns += [path("accounts", include("django.contrib.auth.urls"))]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/pedido/urls.py
from django.urls import path
from .views import *

app_name = "pedido"


urlpatterns = [
    path('item/', pedido_item, name='pedido_Item'),
    #path('', pedido_List, name='pedido_list'),
    path('obs', observacao, name='observacao'),
    path('delete', remover_item, name='remove'),
    path('acres', pedido_acrecimo, name='acrescimo'),
    path('<int:pk>/acrescimo_list', acrescimo_list, name='acrescimo_list'),

      #CONTROLE DE MESAS
    path('mesa_lista/', mesa_list, name='mesa_list'),
    path('mesa_criar/', mesa_criar, name='mesa_criar'),
    path('pedido_criar/', pedido_criar, name='pedido_criar'),
    path('<int:pk>_del_ped', pedido_delete, name='pedido_delete'),
    path('<int:pk>del_mesa', mesa_delete, name='mesa_delete'),
    path('<int:pk>ler_pedido', ler_pedido, name='ler_pedido'),
    path('<int:pk>pronto', pedido_pronto, name='pedido_pronto'),
    path('<int:pk>recebido', pedido_recebido, name='pedido_recebido'),
]

app/pedido/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from loja.models import *
# from cliente.models import *
from produto.models import *

# Create your models here.
class Mesa(models.Model):
    loja = models.ForeignKey(Loja_Model, on_delete=models.CASCADE)
    numero = models.CharField(max_length=10,null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dinheiro = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    pix = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    debito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    credito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fiado = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    frm_pg = models.CharField(max_length=30, null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True, default='aberto')
    objects = models.Manager()


    def __str__(self):
        return str(f' Pedido: {self.pk} Mesa: {self.numero}')
    
    def get_mesa_url(self):
       return reverse_lazy("caixa:fechar_mesa", kwargs={"pk":self.pk})



class Pedido(models.Model):
    dia = models.DateField(auto_now_add=True)
    loja = models.ForeignKey(Loja_Model, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    mesa = models.ForeignKey(Mesa, related_name='ped_mesa',null=True, blank=True, on_delete=models.CASCADE)
    venda = models.CharField(max_length=10, null=True, blank=True)
    pedido = models.TextField(null=True, blank=True)
    total_pedido = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    nome = models.CharField(max_length=200, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    cep = models.CharField(max_length=30, null=True, blank=True)
    endereco = models.CharField(max_length=300, null=True, blank=True)
    numero = models.CharField(max_length=10, null=True, blank=True)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    bairro = models.CharField(max_length=300, null=True, blank=True)
    municipio = models.CharField(max_length=300, null=True, blank=True)
    uf = models.CharField(max_length=30, null=True, blank=True)
    dinheiro = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    pix = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    debito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    credito = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fiado = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    frm_pg = models.CharField(max_length=30, null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True, default='aberto')

    objects = models.Manager()

    def __str__(self):
        return str(f' Pedido: {self.pk} Nome = {self.nome}')


    def get_pedido_url(self):
       return reverse_lazy("caixa:registradora_home", kwargs={"pk":self.pk})
    
    def get_ler_url(self):
       return reverse_lazy("pedido:ler_pedido", kwargs={"pk":self.pk})



class Item(models.Model):
    pedido = models.ForeignKey(Pedido,related_name='item_ped', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto_Model, related_name='item_prod', on_delete=models.CASCADE)
    qt = models.DecimalField(decimal_places=0, max_digits=4, null=True, blank=True)
    preco = models.DecimalField(decimal_places=2, max_digits=14, null=True, blank=True)
    observacao = models.TextField(null=True, blank=True)
    item_acrescimo = models.TextField(null=True, blank=True)

    objects = models.Manager()

    def __str__(self):
        return str(self.pk)


class Acrescimo(models.Model):
    item = models.ForeignKey(Item, related_name='arecimo', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto_Model, related_name='produto', on_delete=models.CASCADE)
    qt = models.DecimalField(decimal_places=0, max_digits=4, null=True, blank=True)
    preco = models.DecimalField(decimal_places=2, max_digits=14, null=True, blank=True)

    objects = models.Manager()

    def __str__(self):
        return str(self.pk)

app/pedido/forms.py
from django import forms
from django.contrib.auth.models import User
from django.shortcuts import render
from .models import *

class Mesa_Form(forms.ModelForm):

    nome=forms.CharField(
        label='Mesa'
    )
    def clean_nome(self):
        data =Pedido.objects.filter(loja=User.loja, nome=self.cleaned_data["nome"] , status="aberto_c", tipo="Mesa")
        if data.exist():
            raise forms.ValidationError('Mesa ja esta aberta, corriga por favor.')
        
        return data
    
    
    class Meta():
        model = Pedido
        fields = ['nome',]
    

app/pedido/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from produto.models import Produto_Model
from pedido.models import Pedido
from caixa.models import Caixa
from django.contrib import messages
from .models import *
from .forms import *

# Create your views here.
# INICIO VITRINE
@login_required
def pedido_item(request):
    pk= request.POST.get('produto_id')
    loja_id = request.POST.get('loja_id')
    pedido=request.POST.get('pedido_id')

    lojaslug=Loja_Model.objects.get(id=loja_id)
    pedido = Pedido.objects.get(id=pedido)
    if pk is not None:
        try:
            product_obj = Produto_Model.objects.get(id=pk)
        except Produto_Model.DoesNotExist:
            print("Mostrar mensagem ao usuário, esse produto acabou!")
            return redirect("cart:home")

        item_prod = Item.objects.filter(produto=pk)
        if item_prod.exists():
            print('1 - sim')
           
            item_prod=Item.objects.filter(produto_id=pk, pedido=pedido.id, item_acrescimo="", observacao="")
            if item_prod.exists():
                print('2 - sim')
                item_prod=Item.objects.get(produto_id=pk, pedido=pedido.id, item_acrescimo="", observacao="")
                item_prod.qt+=1
                item_prod.preco+=item_prod.produto.preco
                item_prod.save()
                print("salvo")
                if  product_obj.estoque == 1:    
                    product_obj.estoque -= 1
                    product_obj.ativo = False
                    product_obj.save()
                else:
                    product_obj.estoque -= 1
                    product_obj.save()

            else:
                print('1 -não')
                item = Item.objects.create(
                    pedido=pedido ,
                    produto= product_obj,
                    qt = 1,
                    preco = product_obj.preco,
                    observacao="",
                    item_acrescimo="",
                )
                item.save()
                print("salvo")
                if  product_obj.estoque == 1:    
                    product_obj.estoque -= 1
                    product_obj.ativo = False
                    product_obj.save()
                else:
                    product_obj.estoque -= 1
                    product_obj.save()

        else:
            item = Item.objects.create(
                pedido=pedido ,
                produto= product_obj,
                qt = 1,
                preco = product_obj.preco,
                observacao="",
                item_acrescimo="",
            )
            item.save()
            print("salvo")
            if  product_obj.estoque == 1:    
                product_obj.estoque -= 1
                product_obj.ativo = False
                product_obj.save()
            else:
                product_obj.estoque -= 1
                product_obj.save()
  
    return redirect("loja:loja_vitrine",slug=lojaslug.loja)

@login_required
def observacao(request):
    loja_id = request.POST.get('loja_id')
    lojaslug=Loja_Model.objects.get(id=loja_id)
    id = request.POST.get("item_id")
    obs = request.POST.get("item_obs")
    qt = request.POST.get("item_qt")
    print(f"id: {id}  obs: {obs} Qt:{qt}")

    item = Item.objects.get(id=id)
    item.observacao = obs
    item.save()
    print("salvo")
    
    return redirect("loja:loja_vitrine",slug=lojaslug.loja)

@login_required
def remover_item(request):
    loja_id = request.POST.get('loja_id')
    lojaslug=Loja_Model.objects.get(id=loja_id)
    id = request.POST.get('remove')
    print("***")
    print(f"id numero{id}")
    print("***")
    pedido = request.POST.get('pedido_id')
    print(pedido)
    acre = Acrescimo.objects.filter(item=id)
    item = Item.objects.get(id=id, pedido=pedido)

    for acre in acre.all():
        acre = Acrescimo.objects.get(id=acre.id)
        produto = Produto_Model.objects.get(id=int(acre.produto))
        produto.estoque += acre.qt * item.qt
        if produto.estoque >= 0 :
            produto.ativo = True    
        
        produto.save()
        acre.delete()

    
    produto = Produto_Model.objects.get(id=item.produto.id)
    produto.estoque+= item.qt
    produto.save()
    item.delete()

    return redirect("loja:loja_vitrine",slug=lojaslug.loja)

@login_required
def pedido_acrecimo(request):
    loja_id = request.POST.get('loja_id')
    id = request.POST.get('add_id')
    pedido= request.POST.get('pedido_id')
    produto = request.POST.get('produto_id')
    item_id = request.POST.get('item_id')
    
    print(f' loja: {loja_id}\n produto: {produto}\n item: {item_id}\n add_id: {id}')

    lojaslug = Loja_Model.objects.get(id=loja_id)
    pedido= Pedido.objects.get(id=pedido)
    produto = Produto_Model.objects.get(id=produto)
    item = Item.objects.get(id=item_id)
    acrescimo = Acrescimo.objects.filter(item=item.id, produto=produto.id)

    if acrescimo.exists():
        if produto.estoque >= item.qt :
 
            print(f' if >= Produto:{produto.estoque} item:{item.qt}')
            acrescimo = Acrescimo.objects.get(item=item.id, produto=produto.id)
            itemf = Item.objects.get(id=item.id)
            if itemf.qt == 1:
                acrescimo.qt += 1
                acrescimo.preco += produto.preco
                acrescimo.save()

                itemf.item_acrescimo=""
                print(f'preco:{itemf.preco} produto{produto.preco}')
                itemf.preco += produto.preco
                itemf.save()
                acresf =  Acrescimo.objects.filter(item = itemf.id)
                for acresf in acresf:
                    itemf.item_acrescimo += f'{acrescimo.produto_nome}-{acresf.qt}<br>'
                    itemf.save() 

                produto.estoque -= itemf.qt
                produto.save()
            else:
                print("mais q 1")
                print(f'antes{acrescimo.qt}')
                acrescimo.qt+= 1
                print(f'depois{acrescimo.qt}')
                acrescimo.preco+=produto.preco*itemf.qt
                acrescimo.save()
                acres =  Acrescimo.objects.filter(item = item_id)
                itemf.item_acrescimo=""
                print(f'preco:{itemf.preco} produto{itemf.produto.preco}')
                itemf.preco = itemf.produto.preco*itemf.qt
                print(f'preco:{itemf.preco} acrescimo{acrescimo.preco}')
                for i in acres:
                    i= Acrescimo.objects.get(id=i.id)
                    itemf.preco+=i.preco
                    itemf.save()
                acresf =  Acrescimo.objects.filter(item = item_id)
                for acresf in acresf:
                    itemf.item_acrescimo+=f'{acrescimo.produto_nome}-{acresf.qt}<br>'
                    itemf.save() 

                produto.estoque -= itemf.qt
                produto.save()    
        else:
            if produto.estoque == item.qt:
                print(f' if == Produto:{produto.estoque} item:{item.qt}')
                acrescimo = Acrescimo.objects.get(item=item.id, produto=produto.id)
                itemf = Item.objects.get(id=item.id)
                if itemf.qt == 1:
                    acrescimo.qt += 1
                    acrescimo.preco += produto.preco
                    acrescimo.save()

                    itemf.item_acrescimo=""
                    print(f'preco:{itemf.preco} produto{produto.preco}')
                    itemf.preco += produto.preco
                    itemf.save()
                    acresf =  Acrescimo.objects.filter(item = itemf.id)
                    for acresf in acresf:
                        itemf.item_acrescimo += f'{acrescimo.produto_nome}-{acresf.qt}<br>'
                        itemf.save() 

                    produto.estoque -= itemf.qt
                    produto.save()
                else:
                    print("mais q 1")
                    print(f'antes{acrescimo.qt}')
                    acrescimo.qt+= 1
                    print(f'depois{acrescimo.qt}')
                    acrescimo.preco+=produto.preco*itemf.qt
                    acrescimo.save()
                    acres =  Acrescimo.objects.filter(item = item_id)
                    itemf.item_acrescimo=""
                    print(f'preco:{itemf.preco} produto{itemf.produto.preco}')
                    itemf.preco = itemf.produto.preco*itemf.qt
                    print(f'preco:{itemf.preco} acrescimo{acrescimo.preco}')
                    for i in acres:
                        i= Acrescimo.objects.get(id=i.id)
                        itemf.preco+=i.preco
                        itemf.save()
                    acresf =  Acrescimo.objects.filter(item = item_id)
                    for acresf in acresf:
                        itemf.item_acrescimo+=f'{acrescimo.produto_nome}-{acresf.qt}<br>'
                        itemf.save() 

                    produto.estoque -= itemf.qt
                    produto.ativo = False
                    produto.save() 
                    
            else:
                print(f' if  Produto:{produto.estoque} item:{item.qt}')
    else:
        print('Não o item_acrescimo não exist')
        if produto.estoque >= item.qt :
            print(f' if >= Produto:{produto.estoque} item:{item.qt}')
            acres = Acrescimo.objects.create(
                item = item,
                produto= produto.id,
                produto_nome = produto.nome,
                preco = produto.preco,
                qt = 1,
            )
            acres.save()
            
            item.item_acrescimo+=f'{acres.produto_nome}-{acres.qt}<br>'
            item.preco+=acres.preco*item.qt
            item.save()

            acres.qt=1
            acres.preco=acres.preco*item.qt
            acres.save()

            produto.estoque -= item.qt
            produto.save()
        else:
            if produto.estoque == item.qt :

app/pedido/templates/pedido/acrescimo.html
{%load static %} 
{% load crispy_forms_tags %} 
{% block content %} 
<div class="container" >
    <strong><h2 class="text-center">Acrescimos</h2></strong>
    <h5>
        {%for acresc in acresc %}
        {{acresc.produto.nome}}-{{acresc.qt}}<br/>
        {%endfor%} 
    </h5>
    
</div>
{%endblock%}

app/pedido/templates/pedido/cardapio.html
{% extends 'home/base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<br/><br/>
<form class="container">
     <div class="container">
         <h1 class="text-center"><strong>Bull Dogs</strong></h1><br/>
          <div class="container">
            <h2 class="text-center"><strong>Lanches</strong></h2>
            {% for produto in produto %}

                <div class="row">
                   <div class="col-md-9" >
                        <h3><strong>{{produto.titulo|safe}}</strong></h3>
                        {{produto.descricao|safe}}
                   </div>
                   <div class="col-md-3" >
                       <br/>
                        <h3><strong>R$ {{produto.preco|safe}}</strong><h3>
                   </div>
                </div>

            {% endfor%}
          </div>
          <div class="container">
              <br/><br/>
              <h1 class="text-center"><strong>Bebidas</strong></h1>
             {% for bebida in bebida %}
                <div class="row">
                   <div class="col-md-9">
                        <h3><strong>{{bebida.titulo|safe}}</strong></h3>
                        {{bebida.descricao|safe}}
                   </div>
                   <div class="col-md-3">
                       <br/>
                        <h3><strong>R$ {{bebida.preco|safe}}</strong><h3>
                   </div>
                </div>
            {% endfor%}
          </div>
     </div>
</form>
{% endblock %}

app/pedido/templates/pedido/criar_mesa.html
<form method="POST" action="{% url 'pedido:mesa_criar' %}" data-endpoint="{% url 'pedido:mesa_criar' %}">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title" id="criar_mesaLabel">N° Mesa :</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <input type="text" name='mesa' class="form-control" >
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Abrir Mesa</button>
        </div>
    </div>

</form>    

app/pedido/templates/pedido/delete_mesa.html
<form method='POST' action="{% url 'pedido:mesa_delete' mesa.id %}" class="form">
    {% csrf_token %}
    <div class="container">

        <input type="hidden" name="mesa_id" value="{{mesa.id}}" />
        <button type='submit'  class='btn btn-light'  >
                <i class="fa fa-close "></i>
        </button>
    </div>
</form>

app/pedido/templates/pedido/delete_pedido.html
<form method='POST' action="{% url 'pedido:mesa_delete' pedido.id %}" class="form">
    {% csrf_token %}
    <div class="container">

        <input type="hidden" name="pedido_id" value="{{pedido.id}}" />
        <button type='submit'  class='btn btn-danger '>
                <i class="fa fa-trash-o "></i>
        </button>
    </div>
</form>

app/pedido/templates/pedido/item_pedido.html
{% load static %} {% load crispy_forms_tags %} {% block content %}
<div class="form-group col-md-12">
    <div class="form-group">
        {% for item in item %} {{item.id}}
        <div style="width: 100%; border-bottom: 1px solid #000000; ">
            <input type="hidden" name="pedido_id" value="{{pedido.id}}">
            <input type="hidden" name="loja_id" value="{{loja.id}}">
            <div class="col-md-12">
                <h5><strong>{{ item.qt|safe }} x {{ item.produto.nome|safe|truncatewords:20}}</strong></h5>
                <div class="row" style="size: 5px;">
                    <div class="col-md-6 ">
                        {{item.observacao}}
                    </div>
                    <div class="col-md-6">
                        {% if item.item_acrescimo %}
                        <div class="container">
                            <a type="button" href="{% url 'pedido:acrescimo_list' item.id %}"  data-toggle="modal" data-target="#exampleModal{{item.id}}">
                            Acrescimos.
                          </a>
                            <div class="modal fade" id="exampleModal{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{item.id}}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">

                                    </div>
                                </div>
                            </div>
                        </div>
                        {%endif%}
                    </div>
                </div>
                <div class="row ">
                    <div class="col-md-4 ">
                        <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#observacao{{item.id}}">
                          <i type='submit'  class="fa fa-edit"></i> 
                        </button>
                        <form method='POST' action='{% url "pedido:observacao" %}' data-endpoint='{% url "pedido:observacao" %}' class="form">
                            {% csrf_token %}
                            <input type="hidden" name="loja_id" value="{{loja.id}}">
                            <div class="modal fade" id="observacao{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{item.id}}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{item.id}}">Observação</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                              </button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="item_id" value="{{ item.id }}">
                                            <div class="col-md-9">
                                                <textarea name="item_obs" cols="30" rows="10">{{item.observacao}}</textarea>
                                            </div>
                                            <div class="col-md-1">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>    
                                
                        </form> 
                    </div>
                    <div class="col-md-4 ">
                            {% if acre_list %}
                            <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#acrescimo{{item.id}}">
                              <i type='submit'  class="fa fa-plus"></i>
                            </button>
                            <input type="hidden" name="loja_id" value="{{loja.id}}">
                            <div class="modal fade" id="acrescimo{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{item.id}}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title" id="acrescimoLabel{{item.id}}">Acrescimos</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="item_id" value="{{ item.id }}">
                                            <div class="col-md-12">
                                                {% for adicionar in adicionar %}
                                                <form method="POST" action="{% url 'pedido:acrescimo' %}" data-endpoint='{% url "pedido:acrescimo" %}' class="form-group">
                                                    {% csrf_token %}
                                                    <div class="container">

                                                        <input type="hidden" name="loja_id" value="{{loja.id}}" />
                                                        <input type="hidden" name="produto_id" value="{{adicionar.id}}" />
                                                        <input type="hidden" name="pedido_id" value="{{pedido.id}}" />
                                                        <input type="hidden" name="add_id" value="{{adicionar.id}}" />
                                                        <input type="hidden" name="item_id" value="{{item.id}}" />
                                                        <div class="row" style="width: 100%; border-bottom: 1px solid #000000;">
                                                            <div class="col-md-6">{{adicionar.nome}}</div>
                                                            <div class="col-md-3">R$: {{adicionar.preco}}</div>
                                                            <div class="col-md-2">
                                                                <span class='submit-span'>
                                                                  <button type='submit' class='btn btn-success' >
                                                                      <i type='submit'  class="fa fa-shopping-cart"></i>
                                                                  </button>
                                                                </span>
                                                              </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                <br/> {% endfor %}
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {%endif%}
                        </div>
                        <div class="col-md-4">
                            <input type="hidden" name="loja_id" value="{{loja.id}}"> {% include 'pedido/remove-product.html' with remove=item.id pedido_id=pedido loja_id=loja.id %}
                        </div>
                        </div>
                    </div>
                </div>
                <br/> {% endfor %}
            </div>
        </div>
        {% endblock %}

app/pedido/templates/pedido/observacao.html
<form  method='POST' action='{% url "produto:observacao" %}'  data-endpoint='{% url "produto:observacao" %}'>
    {% csrf_token %}
    <input type="hidden"  name="item_id" value="{{ item.id }}"/>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Observação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                  <textarea type="textarea" name="item_obs" style="max-width: 15rem; max-height: 10rem;"></textarea>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Anotar Observação</button>
                </div>
            </div>
        </div>
      </div>
    </div>
</form>

app/pedido/templates/pedido/remove-product.html
<form  method='POST' action='{% url "pedido:remove" %}'
  data-endpoint='{% url "pedido:remove" %}'
  class="form"> {% csrf_token %}
  <input type="hidden"  name="remove" value="{{ item.id }}"/>
  <input type="hidden" name="loja_id" value="{{loja.id}}">
  <input type="hidden" name="pedido_id" value="{{pedido.id}}">
  <button type='submit'class='btn btn-link btn-lg' style="color:red;">
    <i class="fa fa-trash" aria-hidden="true"></i>
  </button>
</form>